apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing-minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/nfs_server/saas-apps/dnastorge
    server: 192.168.0.79
  persistentVolumeReclaimPolicy: Retain
  