apiVersion: v1
kind: Secret
metadata:
  name: proxmox-creds
  namespace: crossplane-system
type: Opaque
stringData:
  TF_VAR_proxmox_endpoint: https://192.168.0.66:8006/api2/json
  TF_VAR_proxmox_username: root@pam
  TF_VAR_proxmox_token: root@pam!auto_vm=b6b05fae-cddc-4749-be2a-5517b61cd36a
  TF_VAR_datacenter_user: root
  TF_VAR_datacenter_pass: Pve1LPAFqu4r

# https://192.168.0.66:8006/api2/json
# "root@pam!auto_vm=b6b05fae-cddc-4749-be2a-5517b61cd36a"


# ssh {
#                       agent = true
#                       username = "{{ $vm_username }}"
#                       private_key = file("~/.ssh/id_rsa")
#                   }

# data "local_file" "ssh_public_key" {
#                   count = var.public_key_path != null ? 1 : 0
#                   filename = "~/.ssh/id_rsa.pub"
#                 }
# keys = var.public_key_path != null ? [trimspace(data.local_file.ssh_public_key[0].content)] : []

# env:
                
#                 - name: TF_VAR_proxmox_endpoint
#                   secretKeyRef:
#                     name: proxmox-creds
#                     namespace: crossplane-system
#                     key: credentials
                
#                 - name: TF_VAR_proxmox_username
                  
#                   secretKeyRef:
#                     name: proxmox-creds
#                     namespace: crossplane-system
#                     key: credentials
                
#                 - name: TF_VAR_proxmox_token
                  
#                   secretKeyRef:
#                     name: proxmox-creds
#                     namespace: crossplane-system
#                     key: credentials