apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/nfs_server/home_automation
    server: 192.168.0.79
  #hostPath:
   # path: "/mnt/data/home-assistant-data"
   # type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
