apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab-db.labels" . | nindent 4 }}
  annotations:
    # Preserve this secret across helm upgrades and uninstalls
    helm.sh/resource-policy: keep
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cluster.credentials.username | quote }}
  password: {{ .Values.cluster.credentials.password | quote }}
