image:
  type: nginx
  tag: latest

deployment:
  name: dna-webserver
  app: webserver

configmap:
  name: dna-loadbalancer-cm

service:
  name: dna-load-balancer-service
  port: 80
  nodeport: 30800
  type: NodePort
