persistenceVolume:
  enabled: true
  claimName: home-assistant-volume-claim1
  mountPath: /config

service:
  name: home-assistant-service
  nodePort: 31286
  haPort: 8123
  haPortTarget: 8123
  type: NodePort

deployment:
  name: home-assistant
  replicas: 1
  image:
    repository: ghcr.io/home-assistant/home-assistant
    tag: stable
  #containerPort: 8123
  appSelector: home-assistant