apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: {{ .Values.service.haPort }}
      targetPort: {{ .Values.service.haPortTarget }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
