apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configmap.name }}
data:  
    named.conf: |
        include "/etc/bind/named.conf.local";
    named.conf.local: |
        options {
            directory "/var/cache/bind";
            allow-query { any; };
            recursion no;
        };
        
        zone "dnacloudserver.home" {
                type master;
                file "/etc/bind-generated/db.dnacloudserver.home";
        };
    db.dnacloudserver.home: | 
        $TTL    604800
        @       IN      SOA     ns1.dnacloudserver.home. admin.dnacloudserver.home. (
                                    2         ; Serial
                                604800         ; Refresh
                                86400         ; Retry
                                2419200         ; Expire
                                604800 )       ; Negative Cache TTL
        ;
        @       IN      NS      ns1.dnacloudserver.home.
        ns1     IN      A        PUBLIC_IP    ;
        @       IN      A        HUB_IP       ;
        
        main    IN      A        HUB_IP    ;
        hub     IN      A        HUB_IP    ;
        govee   IN      A        HUB_IP     ;
        homeassistant   IN      A        HUB_IP     ;
        devnest IN      A        HUB_IP     ;