apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  type: NodePort
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
    nodePort: {{ .Values.service.nodePort }}
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
    nodePort: {{ .Values.service.nodePort }}